name: Comment on an issue

on:
  issues:
    types: [opened, edited]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.org.repo.owner,
              repo: context.org.repo.repo,
              labels: ['Triage']
            })
