name: workflow_dispatch

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Event Name
        run: echo -e "This action is triggered by \033[1m${{ github.event_name }}\033[0m event.."
